export const GET_UNIVERSITIES_REQUESTED = 'GET_UNIVERSITIES_REQUESTED';
export const GET_UNIVERSITIES_SUCCESS = 'GET_UNIVERSITIES_SUCCESS';
export const GET_UNIVERSITIES_FAILED = 'GET_UNIVERSITIES_FAILED';
export const GET_UNIVERSITIES = 'GET_UNIVERSITIES';
export const SORT_LIST = "SORT_LIST";
export const SEARCH_LIST = "SEARCH_LIST";
export const ON_CLEAR = "ON_CLEAR";
export const REMOVE_DATA = "REMOVE_DATA"